### ISSUE TITLE
Alpha Release

### ISSUE THREAD

**Issue by dayfine** [dayfine/woflow#3]
- [ ] Hook up a backend for events
- [ ] Use Motion for Drag/Reorder Event
- [ ] Put Back full screen timer
- [ ] Message Icon
- [ ] Feedback System
